### ISSUE TITLE
Support for KDE/SDDM?

### ISSUE THREAD

**Issue by Hoeze** [folixg/pause-on-lock#16]
Can I get this to work on KDE / SDDM?

**Comment by adrianvg** [comment]
Why don't you try it?:-)

**Comment by Hoeze** [comment]
@adrianvg Yes, I'd like to, but what do I have to do therefore? :grin: 

I assume I have to add a KDE option here:
https://github.com/folixg/pause-on-lock/blob/722c6dfa0ba36e46e602a6d513e441efc8cfaea4/pause-on-lock#L23-L40

Is this enough?

**Comment by adrianvg** [comment]
That's what I did when I tested with Mate. After I found it worked, the devs asked me to do a pull request which I did. After that, the code addition was accepted and added to the repo.

Do a 
`$ echo $XDG_CURRENT_DESKTOP `
in a terminal on your computer, then add the text you get to your local git code.

The specific name **org.mate.ScreenSaver** for your desktop environment, you should be able to find using the dconf editor.
