### ISSUE TITLE
KDE not supported after all?

### ISSUE THREAD

**Issue by adrianvg** [folixg/pause-on-lock#18]
**Describe the bug**
Pause-on-lock doesn't pause on lock when using KDE.

**Expected behavior**
Pause-on-lock pauses on lock when using KDE.

**System information:**
 - OS [e.g. Ubuntu 18.04]: Ubuntu 19.10
 - Desktop Environment [e.g. GNOME, Unity, ...]: KDE Plasma 5.16.5, KDE Frameworks 5.62.0, Qt 5.12.4
- pause-on-lock version [e.g. 1.4 or git master branch]: Master

![DeepinScreenshot_select-area_20200110152348-redacted](https://user-images.githubusercontent.com/15629475/72160173-2c676d80-33be-11ea-8924-c3b65c515420.png)

**Comment by folixg** [comment]
This looks like you are not having the latest version. In the latest version [the Error text also includes KDE](https://github.com/folixg/pause-on-lock/blob/818b506fdfb16fe3c87c8fa03d58a054f77eaf5f/pause-on-lock#L85). Is it possible that you are on a different branch or have a different origin configured?

**Comment by adrianvg** [comment]
You might be right. I'll check on the computer ASAP. Thanks for the heads-up!

**Comment by folixg** [comment]
I'm closing this for now, let me know, if you are still having problems.
