### ISSUE TITLE
17.04 problem

### ISSUE THREAD

**Issue by Brett-Holmes** [folixg/pause-on-lock#2]
I know in the description that it says that it works on 16.04, but I tried running this on 17.04 and it does not work.
When running line 3: `dbus-monitor --session "type='signal',interface='com.ubuntu.Upstart0_6'"` 
it returns the error: `dbus-monitor --session "type='signal',interface='com.ubuntu.Upstart0_6'"
signal time=1501614762.488146 sender=org.freedesktop.DBus -> destination=:1.334 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.334"
signal time=1501614762.488193 sender=org.freedesktop.DBus -> destination=:1.334 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.334"`

It seems that gdbus is the only way to use it on 17.04. I'm currently trying to modify my own version to get it to work.

**Comment by folixg** [comment]
I don't have a 17.04 installation right now for testing purposes. But I will have a look into it, when I find the time.

**Comment by folixg** [comment]
So I just fired up a 17.04 VM and did some testing.
With the following changes it should work for 17.04
1. Change the interface, the dbus-monitor is listening to.
``` dbus-monitor --session "type='signal',interface='com.canonical.Unity.Session'" ```
2. As the response for this interface is different, you also need to adapt the `grep` commands.
2.1. For detecting the lock event:
``` if echo $X | grep 'Locked' &> /dev/null; then ```
2.2. For detecting the unlock event:
``` if echo $X | grep 'Unlocked' &> /dev/null: then```

I haven't tested yet, whether this would also work for 16.04 therefore I am not including these changes for now.
