### ISSUE TITLE
Add support for Pop!_OS

### ISSUE THREAD

**Issue by bhedavivek** [folixg/pause-on-lock#20]
**Is your feature request related to a problem? Please describe.**
Would like to add support for Pop!_OS

**Describe the solution you'd like**
Since, Pop!_OS is based on UBUNTU, adding it to the supported list of desktops should enable support for this.

**Comment by bhedavivek** [comment]
PR: https://github.com/folixg/pause-on-lock/pull/21

**Comment by folixg** [comment]
Closed by #21
