### ISSUE TITLE
XFCE support

### ISSUE THREAD

**Issue by mariaczi** [folixg/pause-on-lock#22]
For XFCE support we have:

```
$ echo $XDG_CURRENT_DESKTOP
XFCE
```
So, dbus-monitor command will be:
`dbus-monitor --session "type='signal',interface='org.xfce.ScreenSaver',member='ActiveChanged'"`

Tested and working for me.

**Comment by folixg** [comment]
Thanks for the suggestion. Will include it in the next release.
