### ISSUE TITLE
Gjs Script

### ISSUE THREAD

**Issue by JasonLG1979** [folixg/pause-on-lock#5]
Not really an issue but here is an example of a Gjs script that I threw together after I read about your script at OMGUbuntu. My script however works with any player(that has a MPRIS interface ofc) and supports most desktops except Unity(couldn't find the DBus docs and didn't see the point with it being dead). Just thought I might offer a little inspiration :)

https://gist.github.com/JasonLG1979/d631cea4e8d566b5acecc5b115c1d9df

**Comment by folixg** [comment]
I created the script, when I was using Unity and missing this feature.
I'll leave this issue open, so people who are looking for a solution for other desktops (which will obviously be happening in the foreseeable future) maybe find it here.
I'm not really familiar with js, but as far as I understand it, your script does not resume the paused player on unlock, right?

**Comment by JasonLG1979** [comment]
No it does not resume at unlock. I don't even know if I like that as an automatic feature. I'm thinking about making my script a GNOME Shell extension that could be a user option.

**Comment by folixg** [comment]
Go for it. As i use i3wm now I probably won't be porting the script to GNOME and it will be useless when Ubuntu doesn't use Unity anymore. And a GNOME shell extension would definitely be nicer than a shell script.

**Comment by JasonLG1979** [comment]
I'm currently working on fading the volume in and out to compliment the pause/play.

**Comment by JasonLG1979** [comment]
Here's an updated version of the script that:

1. Stops the player instead of Pausing it if the player's MPRIS canPause prop is False.
2. Resumes playback if the current playback status is not 'Stopped' and the player's MPRIS canPlay prop is True and it was previously playing ofc.

https://github.com/JasonLG1979/ScreenSaverPause

**Comment by JasonLG1979** [comment]
Making it a GNOME Shell extension is basically a bust because:

1. Extensions are disabled/destroyed when the screen is locked and initted/enabled when it's unlocked.

2. Extensions are disabled before they can receive the signal that the screen was locked.

So the Extension would init and enable/disable just fine it just wouldn't do anything for the above reasons.

**Comment by JasonLG1979** [comment]
> Making it a GNOME Shell extension is basically a bust

Scratch that. Number 1 still applies. Once the screen is locked I can't figure out how to resume but this stupid simple extension I wrote based on my script will Pause/Stop players when the screen starts to fade out before it locks and will resume them if the fade is interrupted at least. I call it Morphine. Kinda a play on the Caffeine extension's name.

https://github.com/JasonLG1979/gnome-shell-extensions-morphine

**Comment by folixg** [comment]
Since this script now is able to handle GNOME sessions, I'm closing the issue.
