### ISSUE TITLE
Documentation about how to install

### ISSUE THREAD

**Issue by mhalano** [folixg/pause-on-lock#6]
Should have any information on README about how use this script, like where to put it, how to set execution permission, what are the dependencies and so on.

**Comment by folixg** [comment]
The usage is pretty straight forward:
1. Put ```pause-on-lock.sh``` in any directory of your choosing.
2. Set the executable bit (i.e. ```chmod +x pause-on-lock.sh```).
3. Run it.

Optionally you can also add it to *[Startup Applications](https://help.ubuntu.com/stable/ubuntu-help/startup-applications.html)*, so it is run every time you log in.

**Comment by mhalano** [comment]
Yeah, that's simple. But the goal is always have this running to a good experience. May be put a line on ~/.profile to start automagically during session?

**Comment by folixg** [comment]
Since the script only works when Unity is running, I think an entry in Unity Startup Applications is preferable over an entry in ~/.profile.
